
const stats = [['140+', 'Active Clients'], ['17+', 'Team Advisors'], ['256+', 'Projects Done'], ['7+', 'Glorious Years']]
const testimonials = [
  ['Radhe Goind', 'Founder & CEO of Avenue Real Estate', 'AdyGuru is one of the best digital marketing gurus who trained me about Facebook Ads. The communication is professional and the support is excellent.', '/testimonial4.webp'],
  ['Shashank Vashista', 'CEO of Fine Architecture', 'I appreciated their quick communication and flexibility. They worked within our strategy with impressive speed and accuracy.', '/testimonial1.webp'],
  ['Harish Pandey', 'Founder & CEO of Sonica Hardware', 'There is a dedicated team there, and they respond promptly to queries. Their advice is practical and valuable.', '/testimonial3.webp'],
  ['Mithlesh Kumar', 'Developer', 'The AdyGuru team was amazing to work with during the design process. They guided us through every step.', '/testimonial2.webp'],
]
const team = [['Diya Nair', 'Brand Strategist Specialist', '/team1.webp'], ['Vanya Desai', 'Influencer Marketing Specialist', '/team2.webp'], ['Suresh Bhatia', 'Meta Ads Expert', '/team4.webp'], ['AdyGuru', 'CEO & Founder', '/team3.webp'], ['Aayush Gautam', 'SEO Expert', '/team5.webp'], ['Ahaana Gupta', 'Social Media Manager', '/team6.webp']]
function PageShell({ eyebrow, title, children }) {
  return <main className="about-dark min-h-screen bg-[#060605] text-white"><section className="bg-[#0A0A0A] px-6 py-20 text-white lg:px-8"><div className="mx-auto max-w-7xl"><p className="font-bold uppercase tracking-[0.25em] text-[#e0bd68]">{eyebrow}</p><h1 className="mt-4 text-5xl font-black sm:text-7xl">{title}</h1><p className="mt-5 text-neutral-300">Home <span className="mx-2 text-[#e0bd68]">/</span> {title}</p></div></section>{children}</main>
}
export function AboutUs() { return <PageShell eyebrow="About Us" title="Grow Your Business With AdyGuru"><section className="about-intro px-6 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><div><div className="about-intro__eyebrow">ABOUT ADYGURU <span /></div><h2 className="about-intro__title">Over <em>10+</em> Years Helping<br className="hidden sm:block" /> Companies Reach Their<br className="hidden sm:block" /> Goals.</h2><p className="about-intro__copy">AdyGuru is a creative, high-energy Entrepreneur Digital Coach who helps people use the power of social media to sell products and services. Ady works with entrepreneurs across the world using marketing strategies to help them succeed online.</p><a href="https://chat.whatsapp.com/J4xvJNgZOhEJJlD48gAODT" target="_blank" rel="noreferrer" className="about-intro__button">◉ <span /> Join WhatsApp Community <b>→</b></a></div><div className="founder-card"><div className="founder-card__image"><div className="founder-card__glow" /><img src="/team3.webp" alt="Sultan Singh Prajapat, CEO and Founder of AdyGuru" /><p>Build<br />Grow<br />Scale</p></div><div className="founder-card__caption"><span>CEO &amp; FOUNDER</span><strong>Sultan Singh Prajapat</strong></div></div></div></section><section className="about-stats px-6 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-px overflow-hidden rounded-2xl bg-[#d4af57]/20 md:grid-cols-4">{stats.map(([number, label]) => <div key={label} className="bg-[#141411] p-6 text-center"><p className="text-4xl font-black">{number}</p><p className="mt-2 text-sm font-bold uppercase tracking-wide text-neutral-300">{label}</p></div>)}</div></section><Cta /></PageShell> }
export function Testimonials() {
  return <PageShell eyebrow="Testimonials" title="What Our Clients Say"><section className="testimonial-grid px-6 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-2">{testimonials.map(([name, role, quote, image]) => <article key={name} className="testimonial-card"><div className="testimonial-card__top"><img src={image} alt={name} /><span>“</span></div><p className="testimonial-card__quote">{quote}</p><div className="testimonial-card__author"><strong>{name}</strong><small>{role}</small></div><i aria-hidden="true" /></article>)}</div></section><Cta /></PageShell>
}
export function OurTeam() {
  return <PageShell eyebrow="Our Team" title="Meet The Team Behind Growth"><section className="team-section px-6 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 sm:grid-cols-2 lg:grid-cols-3">{team.map(([name, role, image]) => <article key={name} className="team-card"><div className="team-card__photo"><img src={image} alt={name} /><span>{name[0]}</span></div><div className="team-card__info"><h2>{name}</h2><p>{role}</p><i aria-hidden="true" /></div></article>)}</div></section><Cta /></PageShell>
}
function Cta() { return <section className="about-cta-wrap px-6 pb-20 lg:px-8"><div className="about-cta mx-auto max-w-7xl"><div><p className="about-cta__eyebrow">Generate Sales With Us</p><h2>Generate <span>1000&apos;s Leads</span><br className="hidden sm:block" /> Using Paid Marketing And SEO</h2></div><a href="/contact-us">Start Now <span>→</span></a></div></section> }
export default AboutUs
